updated to use the latest version of limine for x86_64 kernel

diff --git a/kernel/get-deps b/kernel/get-deps
--- a/kernel/get-deps
+++ b/kernel/get-deps
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-set -ex
+set -e
 
 srcdir="$(dirname "$0")"
 test -z "$srcdir" && srcdir=.
@@ -11,70 +11,41 @@ clone_repo_commit() {
     if test -d "$2/.git"; then
         git -C "$2" reset --hard
         git -C "$2" clean -fd
-        if ! git -C "$2" checkout $3; then
+        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
             rm -rf "$2"
         fi
     else
         if test -d "$2"; then
-            set +x
-            echo "error: '$2' is not a Git repository"
+            echo "error: '$2' is not a Git repository" 1>&2
             exit 1
         fi
     fi
     if ! test -d "$2"; then
         git clone $1 "$2"
-        if ! git -C "$2" checkout $3; then
+        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
             rm -rf "$2"
             exit 1
         fi
     fi
 }
 
-download_by_hash() {
-    DOWNLOAD_COMMAND="curl -Lo"
-    if ! command -v $DOWNLOAD_COMMAND >/dev/null 2>&1; then
-        DOWNLOAD_COMMAND="wget -O"
-        if ! command -v $DOWNLOAD_COMMAND >/dev/null 2>&1; then
-            set +x
-            echo "error: Neither curl nor wget found"
-            exit 1
-        fi
-    fi
-    SHA256_COMMAND="sha256sum"
-    if ! command -v $SHA256_COMMAND >/dev/null 2>&1; then
-        SHA256_COMMAND="sha256"
-        if ! command -v $SHA256_COMMAND >/dev/null 2>&1; then
-            set +x
-            echo "error: Cannot find sha256(sum) command"
-            exit 1
-        fi
-    fi
-    if ! test -f "$2" || ! $SHA256_COMMAND "$2" | grep $3 >/dev/null 2>&1; then
-        rm -f "$2"
-        mkdir -p "$2" && rm -rf "$2"
-        $DOWNLOAD_COMMAND "$2" $1
-        if ! $SHA256_COMMAND "$2" | grep $3 >/dev/null 2>&1; then
-            set +x
-            echo "error: Cannot download file '$2' by hash"
-            echo "incorrect hash:"
-            $SHA256_COMMAND "$2"
-            rm -f "$2"
-            exit 1
-        fi
-    fi
-}
+rm -f .deps-obtained
 
 clone_repo_commit \
-    https://github.com/osdev0/freestnd-c-hdrs-0bsd.git \
-    freestnd-c-hdrs-0bsd \
-    0353851fdebe0eb6a4d2c608c5393040d310bf35
+    https://codeberg.org/OSDev/freestnd-c-hdrs-0bsd.git \
+    freestnd-c-hdrs \
+    097259a899d30f0a4b7a694de2de5fdda942e923
 
-download_by_hash \
-    https://github.com/osdev0/cc-runtime/raw/dcdf5d82973e77edee597a047a3ef66300903de9/cc-runtime.c \
-    src/cc-runtime.c \
-    199907f5303ab15a963377fabcc1f2ee736e4ed18d54c59aab08345aa5485e8a
+clone_repo_commit \
+    https://codeberg.org/OSDev/cc-runtime.git \
+    cc-runtime \
+    dae79833b57a01b9fd3e359ee31def69f5ae899b
 
-download_by_hash \
-    https://github.com/limine-bootloader/limine/raw/97c31196a9aec28b36ed9ff64d6df77a061c3d9b/limine.h \
-    src/limine.h \
-    3a018a8326adb5e6cff14a8595c775fd88235eb3e5fde4a135132b6398d165d5
+clone_repo_commit \
+    https://codeberg.org/Limine/limine-protocol.git \
+    limine-protocol \
+    42e836e30242c2c14f889fd76c6f9a57b0c18ec2
+
+touch .deps-obtained
+
+printf "\nDependencies obtained successfully.\n"
